kookmin-sw/capstone-2025-21

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
- Back/allergy/src/main/java/com/capstone/allergy/dto/ImageAnalysisRequestDto.java
- Back/allergy/src/main/java/com/capstone/allergy/service/ImageAnalysisService.java
- closed #55
- 
- ImageAnalysisRequestDto 생성
- AiImageAnalysisClient 수정 (requestAnalysis)
- ImageAnalysisService 수정
-
> [Chore] 사용자 정보 및 ai 요청 코드 수정 #55

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Chore] ai request error message #62

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Fix] image translate function error #64

- AI/app.py
> [Chore] 바운딩 박스 정보 추가

- Back/allergy/src/main/java/com/capstone/allergy/controller/HomeController.java
> [Chore] homecontroller errorcode 500 추가 #74

- AI/app.py
- closed #78 
- app.py 입력 양식 및 자잘한 내용 수정
-
> [Chore] app.py 입력 양식 및 자잘한 부분 수정

- Back/allergy/src/main/java/com/capstone/allergy/cache/ImagePathCache.java
- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageController.java
> [Chore] remove analyze requestBody #83

- AI/.gitignore
- AI/app.py
- closed #92
- app.py: recommendations 외에 전체 메뉴판 정보 및 알러지 정보 return하도록 수정
-
> [Chore] app.py return값 수정#92

- AI/requirements.txt
- closed #97
- requirements.txt 수정(gpu 환경에서 동작하도록)
-
> [Chore] requirements.txt 수정

- Back/allergy/src/main/java/com/capstone/allergy/dto/MenuTranslationResultDto.java
> [Chore] MenuTranslationResultDto 오타 수정 #108

- Back/allergy/src/main/java/com/capstone/allergy/controller/RestaurantController.java
- Back/allergy/src/main/java/com/capstone/allergy/dto/RestaurantResponseDto.java
- Back/allergy/src/main/java/com/capstone/allergy/service/RestaurantService.java
> [Chore] /api/restaurant/recommend 완료 #108

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageController.java
- Back/allergy/src/main/java/com/capstone/allergy/exception/GlobalExceptionHandler.java
- Back/allergy/src/main/resources/application.properties
> [Chore] 이미지 크기 수정 #114

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Chore] swagger 추가 #125

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Chore] analyze translate swagger 수정 #132

- Back/allergy/src/main/java/com/capstone/allergy/service/ImageAnalysisService.java
> [Fix] nationality langcode #134

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Chore] print allergy in translate-image #136

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
- Back/allergy/src/main/resources/application.properties
> [Chore] translate-image imageUrl #138

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Fix] translate-image swagger 오타 #140

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Fix] 번역 이미지 투명도 수정 #142

- Back/allergy/src/main/java/com/capstone/allergy/dto/RecommendationsDto.java
> [Chore] 이미지 분석 결과 유사도 퍼센트 #144

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Chore] analyze swagger #146

- AI/app.py
- closed #149
- app.py 알러지 정보 추가
-
> [Chore] 알러지 정보 추가#149

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
- Back/allergy/src/main/java/com/capstone/allergy/dto/ImageAnalysisResultDto.java
- Back/allergy/src/main/java/com/capstone/allergy/dto/RecommendationsDto.java
- Back/allergy/src/main/java/com/capstone/allergy/service/ImageAnalysisService.java
> [Chore] Analyze 분석 결과 수정 #158

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
> [Chore] top_k 삭제 #160

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
- Back/allergy/src/main/java/com/capstone/allergy/exception/GlobalExceptionHandler.java
- Back/allergy/src/main/java/com/capstone/allergy/service/ImageAnalysisService.java
> [Chore] 에러 처리 #162

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
> [Chore] swagger 수정 #164

- Back/allergy/src/main/java/com/capstone/allergy/controller/ImageAnalysisController.java
- Back/allergy/src/main/java/com/capstone/allergy/exception/GlobalExceptionHandler.java
> [Chore] swagger 오류 추리 #166

- Back/allergy/src/main/java/com/capstone/allergy/config/WebConfig.java
> [Chore] 이미지 접근 허용 #172

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
> [Chore] ai ip 수정 #175

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
- Back/allergy/src/main/java/com/capstone/allergy/dto/AllergenDto.java
- Back/allergy/src/main/java/com/capstone/allergy/dto/ImageAnalysisResultDto.java
- Back/allergy/src/main/java/com/capstone/allergy/service/ImageAnalysisService.java
> [Chore] 이미지 분석 결과 Dto 수정 #177

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
> [Fix] AI Translate URL 수정 #179

- Back/allergy/src/main/java/com/capstone/allergy/client/AiImageAnalysisClient.java
> [Fix] translate json 로그 출력 #181

- Back/allergy/src/main/java/com/capstone/allergy/config/RestTemplateConfig.java
> [Chore] RestTemplate timeout #185

- Back/allergy/build.gradle
> [Chore] 타임아웃 제거 #189

- Back/allergy/src/main/resources/application-prod.properties
> [Fix] dummymod prod #195
